-- Tabla Rol
-- rol_id tipo numero 8 numeros a la derecha con 0 decimales
CREATE TABLE rol
  (
    rol_id NUMBER(2,0) GENERATED BY DEFAULT AS IDENTITY
    START WITH 1 PRIMARY KEY,
    nombre VARCHAR2( 50 ) NOT NULL
  );
-- usuario
-- usuario_id tipo numero 8 numeros a la derecha con 0 decimales
CREATE TABLE usuario
  (
    usuario_id NUMBER(8,0) GENERATED BY DEFAULT AS IDENTITY
    START WITH 1 PRIMARY KEY,
    nombre VARCHAR2( 50 ) NOT NULL,
    a_paterno VARCHAR2( 50 ),
    a_materno VARCHAR2( 50 ),
    id_trol NUMBER( 2,0 ),
    CONSTRAINT fk_usuario_rol FOREIGN KEY( id_trol )
    REFERENCES rol( rol_id ) 
    ON DELETE SET NULL
  );
